# Generated by Django 4.2.18 on 2025-01-16 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exhibits', '0004_rename_name_artist_first_name_alter_artwork_artist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Places',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.AlterField(
            model_name='artwork',
            name='artist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='exhibits.artist'),
        ),
        migrations.CreateModel(
            name='OutsidePlaces',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('id_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exhibits.places')),
            ],
        ),
        migrations.CreateModel(
            name='InsidePlaces',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('room', models.CharField(max_length=100)),
                ('id_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exhibits.places')),
                ('localization_in', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exhibits.insideplaces')),
            ],
        ),
    ]
