# Generated by Django 4.2.18 on 2025-01-26 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibits', '0005_places_alter_artwork_artist_outsideplaces_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='insideplaces',
            old_name='room',
            new_name='name',
        ),
        migrations.AddField(
            model_name='insideplaces',
            name='place_type',
            field=models.CharField(choices=[('warehouse', 'Magazyn'), ('gallery', 'Galeria'), ('room', 'Sala')], default='room', max_length=50),
            preserve_default=False,
        ),
    ]
