# Generated by Django 4.2.18 on 2025-01-26 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exhibits', '0006_rename_room_insideplaces_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_from', models.DateField()),
                ('date_to', models.DateField(blank=True, null=True)),
                ('id_artwork', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exhibits.artwork')),
                ('id_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exhibits.places')),
            ],
        ),
    ]
